services:
  mysql:
    image: mysql:8.0
    container_name: quickbits_mysql
    environment:
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: quickbits
      MYSQL_USER: web
      MYSQL_ROOT_PASSWORD: rootassword123
    ports:
      - "3030:3306"
    networks:
      - quickbit_net
    volumes: 
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql -u web -pass"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: quickbits_img
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: quickbits_app
    ports:
      - "4000:4000" 
    networks:
      - quickbit_net
    depends_on:
      mysql:
        condition: service_healthy
    command: /app/main -addr=:4000 -dsn=web:pass@tcp(quickbits_mysql:3306)/quickbits?parseTime=true -htmlPath=""

volumes:
  mysql_data: 

networks:
  quickbit_net: